version: '3.3'
services:
  frontend:
    image: dod/frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: dockerfile
    environment:
      URL: 'http://localhost:18080/api'
    ports:
      - "8080:8080"
    depends_on:
      - backend
  backend:
    image: dod/backend
    restart: unless-stopped
    build:
      context: backend
      dockerfile: dockerfile
    ports:
      - "18080:18080"
    volumes:
      - ./backend/config.yml:/app/config.yml:ro
      - ./Demos:/app/Demos:rw
      - ./log:/app/log:rw
    depends_on:
      - db
  db:
    image: postgres:15.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dod_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/:ro
      # persistend storage for database. uncomment when running in production
      # - ./data:/var/lib/postgresql/data:rw
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db